### PR TITLE
Refactoring and Shop additions

### PR DESCRIPTION
**Pull request by strburst**
I've done a bunch of refactoring to `GameManager`/`WorldMap`/`Player`, and made some additions to `Shop`:
- Move information about what tiles a player owns to `WorldMap`
- Add spoilage ratios/food usage info to `Shop` (TODO: calculate usage for all other resources)
- Move information about starting money to `Race`
- Make `calculateTurnOrder` in `GameManager` just two lines! :smile:

Please give feedback/merge. Also, @jgkamat and everyone else, could you test this to see if it works on your machine? I'm getting a "Scene hasn't been loaded!" when I try to hit "Start Game".

### CODE REVIEW

**Comment by jgkamat** [comment]
Looks good to me! :+1:

**Comment by strburst** [comment]
We need to fix that `NullPointerException` in `PlayController` somehow, either by not initializing a `WorldMap` until we know about all the players, or letting players be dynamically added to `WorldMap`.

The latter is pretty inelegant, but I don't know how to do the former.

**Comment by jgkamat** [comment]
I'm trying to find any usages of initialize() and I cant find any, so I'm assuming they have to be loaded when the program starts. IMO the playmanger shouldn't contain ANYTHING, if at all, it should be subclasses or alike things.

**Comment by strburst** [comment]
After poking around, I can see in the `start` method in `MULE`, all the fxml files/controllers are loaded when the game starts; there must be an associated call to `initialize` in the `loadScene` method in `SceneLoader`.

**Comment by jgkamat** [comment]
Hmm, we could possibly add it there, but I still think that this data shouldn't be in the controllers. Controllers are on the view side, while this info should be in the model.

**Comment by strburst** [comment]
I've fixed some bugs my changes introduced (e.g. in `calculateTurnOrder`). I'm still getting this annoying issue where some of the tiles don't show up properly; I'm not sure why. See below.

buggytiles

Also, there will be some merge conflicts with @joshhting's branch to fix.

**Comment by strburst** [comment]
@MountainRange/peaks hopefully we can merge this and Josh's changes soon so I can get to work on production computations.

**Comment by jgkamat** [comment]
Huh, I'll figure out whats going on there

**Pull request merged**
