### PR TITLE
Added more random events and round events

### PR DESCRIPTION
**Pull request by jgkamat**

### CODE REVIEW

**Comment by jgkamat** [comment]
@rmkeezer could you fix the tests and merge this?

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Code Review Recommended. Check Details Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=MountainRange&toolchainId=matthew_test_please_delete&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=MountainRange&toolchainId=matthew_test_please_delete&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=8779e7b4-5ccd-432f-b1fe-8596a35f3bc9&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=8779e7b4-5ccd-432f-b1fe-8596a35f3bc9&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=8779e7b4-5ccd-432f-b1fe-8596a35f3bc9&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=4e072043-130a-41da-b0ba-2875f9e67103&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://console.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=ecd9bfdb-842a-4e98-9b99-0c8574f6f076&branch=randomevents&env_id=ibm:yp:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=matthew_test_please_delete&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=8779e7b4-5ccd-432f-b1fe-8596a35f3bc9&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=matthew_test_please_delete&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://console.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=ecd9bfdb-842a-4e98-9b99-0c8574f6f076&branch=randomevents&env_id=ibm:yp:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=matthew_test_please_delete&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=matthew_test_please_delete3&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=039d2fa9-21bd-4bde-8d5e-a16dbf33a442&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=a5724662-77c3-4fd1-9b15-83b6950aacd6&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=a5724662-77c3-4fd1-9b15-83b6950aacd6&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=matthew_test_please_delete&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=3dc79982-8427-4452-9306-b33f537110b1&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=3dc79982-8427-4452-9306-b33f537110b1&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=ec6ab45d-93e6-44bd-b8b0-4d927e3d1119&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=3dc79982-8427-4452-9306-b33f537110b1&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=ec6ab45d-93e6-44bd-b8b0-4d927e3d1119&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=33dd0584-928b-4556-8139-2d9b045b1be3&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that no highly error prone files were touched by this pull request. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=3dc79982-8427-4452-9306-b33f537110b1&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=94b68ac8-33f5-4520-b4a1-840a85dcfac4&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=3dc79982-8427-4452-9306-b33f537110b1&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=3dc79982-8427-4452-9306-b33f537110b1&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by rmkeezer** [comment]
**Devops Insights Suggestion**
Devops Insights detected that highly error prone files were touched by this pull request, code review is recommended. Click here for more info:
https://dev-console.stage1.bluemix.net/devops/insights/statuscheck?pull_id=70.0&repo=MULE&account=rmkeezer&toolchainId=3dc79982-8427-4452-9306-b33f537110b1&branch=randomevents&env_id=ibm:ys1:us-south

**Comment by jgkamat** [comment]
matthew plz

**Pull request closed without merging**
