### PR TITLE
Add some sick beats

### LINKED ISSUE #51: Chiptunes music

### PR DESCRIPTION
**Pull request by jgkamat**
Add some :sunglasses: chiptunes

Please see if they work on your systems/any complaints

@joshhting volume slider works too.

closes #51

### CODE REVIEW

**Comment by joshhting** [comment]
For me it crashed on startup

```
:run
help
Nov 04, 2015 11:27:02 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.40 by JavaFX runtime of version 8.0.11
Exception in Application start method
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:367)
    at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:305)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:894)
    at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
    at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: UUID was null!
    at io.github.jgkamat.JayLayer.PlayingManager.silentKill(PlayingManager.java:73)
    at io.github.jgkamat.JayLayer.Playlist.stop(Playlist.java:82)
    at io.github.jgkamat.JayLayer.JayLayer.stopPlaylist(JayLayer.java:150)
    at io.github.mountainrange.mule.controllers.MainController.onSetScene(MainController.java:34)
    at io.github.mountainrange.mule.SceneLoader.setScene(SceneLoader.java:98)
    at io.github.mountainrange.mule.MULE.start(MULE.java:74)
    at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
    at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
    at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application io.github.mountainrange.mule.MULE
:run FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 31.524 secs
Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

**Comment by jgkamat** [comment]
I'll figure this out, but I don't get it on my computer... weird

**Comment by joshhting** [comment]
I'll try updating my javafx version and see if that does anything

**Comment by jgkamat** [comment]
Dosen't seem like it would fix anything though. I think this is on my end.

**Comment by jgkamat** [comment]
It looks like you have an older version of the library? Thats weird though, it should force download the newer one. 
could you remove your gradle cache and try again? Mines at `~/.gradle/caches`

**Comment by jgkamat** [comment]
Yah, it looks like you have an older version of the file... Thats really, really werid. (especially because the older version would fail to compile...)

The line numbers could only have come from that older version.

If that dosent work, make the `[4.1.1,)` into simply `4.1.1` in build.gradle (for JayLayer)

**Comment by jgkamat** [comment]
Just updated the README with the new requirements. Any objections to merging this? 
(last chance to change the sound files...)

@MountainRange/peaks

**Comment by strburst** [comment]
LGTM :+1:

**Comment by jgkamat** [comment]
cool, merging now! =)

**Pull request merged**
