### PR TITLE
Fixed bad indentation in build.gradle

### PR DESCRIPTION
**Pull request by jgkamat**
I fixed the bad indentation problems we were having in build.gradle!
hooray!

### CODE REVIEW

**Comment by joshhting** [comment]
Looks good to me!

**Comment by jgkamat** [comment]
Oh no, It looks like it dosent pass tests! This is a critical bugfix, so I'm going to merge this anyway, because I did a review before I pushed!

**Comment by joshhting** [comment]
The checks might not be green but that's just because it's Halloween and GitHub is changing the colors of everything. Go ahead and merge!

**Comment by jgkamat** [comment]
Here goes!

**Pull request merged**
