### PR TITLE
Randomizemap

### PR DESCRIPTION
**Pull request by jgkamat**
Random map is random. Uncomment the thingy next to go back in playcontroller and press back to test it out. Seems to work welll. We need a proper background though...

### CODE REVIEW

**Comment by jgkamat** [comment]
Working on fixing the tests

**Comment by jgkamat** [comment]
I need to find a solution to the shop moving currently, don't merge.

**Comment by jgkamat** [comment]
@MountainRange/peaks should we make the shop actually find the new shop location or should we not move it. I want to have it refactored either way eventually...

**Comment by joshhting** [comment]
How about we get rid of the whole clicking on the town thing and replace that with highlighting it with the arrow keys and hitting space to interact with it. Just like how we handle buying tiles and installing mules

**Comment by jgkamat** [comment]
If someone wants to fix that and push it to this branch, that would be great!

**Comment by joshhting** [comment]
I'll do it

**Comment by jgkamat** [comment]
I'm going to merge this before the summit, as any shop changes need to take place outside these classes, so we can do them later.

**Pull request merged**
